### ISSUE TITLE
SBCL: package lock violation when interning %vector-widetag-and-n-bits

### ISSUE THREAD

**Issue by christophejunke** [sionescu/static-vectors#9]
Since commit bfb7de5, SBCL renamed `%vector-widetag-and-n-bits` as `%vector-widetag-and-n-bits-shift`, which makes compilation fail in static-vectors's `impl-sbcl.lisp` (the previous symbol does not exist, so it tries to intern it, which fails due to package locks).

A simple solution is to rename it too in `impl-sbcl.lisp`, but that will then break with previous versions of SBCL. Since there are not many such changes, you could also support both  (not sure how important it is for you):

```
(defun vector-widetag-and-n-bits (type)
  (let ((upgraded-type (upgraded-array-element-type type)))
    (case upgraded-type
      ((nil t) (error "~A is not a specializable array element type" type))
      (t       (#.(or (find-symbol (string '#:%vector-widetag-and-n-bits) "SB-IMPL")
                      (find-symbol (string '#:%vector-widetag-and-n-bits-shift) "SB-IMPL")
                      (error "SBCL did it again"))
                  type)))))
```

Tested with `SBCL 1.3.13.7.master.2-4741dfe`

**Comment by deem0n** [comment]
I was affected by this issue too while (ql:quickload :ningle)
Any chance it will be fixed soon?

**Comment by Davidbhodge** [comment]
I have the same issue. I note that Christophe's solution works for SBCL 1.3.13 and once applied the reported error from deemon5 above does not occur.

**Comment by dptd** [comment]
I am running SBCL 1.3.13 and @christophejunke solutions worked for me. Thanks!

**Comment by sionescu** [comment]
Thanks for the report. Fix committed.

**Comment by dunn** [comment]
I'm still seeing this with static vectors 1.8.2 and SBCL while compiling fast-io: https://gist.github.com/dunn/720955c0a70afd976b88f200e2718612#file-fast-io-install-L3399-L3405
